image: gitpod/workspace-full:2023-02-27-14-39-56
tasks:
  - name: install-dependencies
    before: |
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
    init: |
    command: | 
      clear
github:
  prebuilds:
    main: true
ports:
  - port: 1-9999
    onOpen: ignore
vscode:
   extensions:
    - https://github.com/DataStax-Academy/katapod/releases/download/stable/katapod-stable.vsix