tasks:
  - name: install-dependencies
    before: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      curl https://katapod-file-store.s3.us-west-1.amazonaws.com/dse-6.8.33-bin.tar.gz \
        --output dse-6.8.33-bin.tar.gz
    init: |
      pip install -U cqlsh
    command: | 
      source /home/gitpod/.astra/cli/astra-init.sh
